services:
  mysql:
    image: mysql:8.0
    container_name: todolist_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: regio
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped